(function(){
'use strict';
const $=id=>document.getElementById(id), n=v=>Number.isFinite(parseFloat(v))?parseFloat(v):0, money=v=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:2}):'—';
function calc(){
 const pv=n($('pv').value),ev=n($('ev').value),ac=n($('ac').value),bac=n($('bac').value),dur=n($('duration').value);
 const sv=ev-pv,cv=ev-ac,spi=pv?ev/pv:0,cpi=ac?ev/ac:0,eac=cpi?bac/cpi:0,etc=eac-ac,vac=bac-eac,tcpiB=(bac-ac)?(bac-ev)/(bac-ac):0,tcpiE=(eac-ac)?(bac-ev)/(eac-ac):0,fd=spi?dur/spi:0;
 $('sv').textContent=money(sv); $('cv').textContent=money(cv); $('spi').textContent=spi?spi.toFixed(2):'—'; $('cpi').textContent=cpi?cpi.toFixed(2):'—'; $('eac').textContent=money(eac); $('etc').textContent=money(etc); $('vac').textContent=money(vac); $('forecastDuration').textContent=fd?fd.toFixed(1)+' '+$('durationUnit').value:'—';
 $('healthRows').innerHTML='<tr><td>Schedule Variance</td><td>EV − PV</td><td>'+money(sv)+'</td><td>'+(sv>=0?'Earned value is at or ahead of planned value.':'Earned value is behind planned value.')+'</td></tr><tr><td>Cost Variance</td><td>EV − AC</td><td>'+money(cv)+'</td><td>'+(cv>=0?'Value earned is at or above actual cost.':'Actual cost is higher than earned value.')+'</td></tr><tr><td>Schedule Performance Index</td><td>EV ÷ PV</td><td>'+(spi?spi.toFixed(2):'—')+'</td><td>1.00 is on plan; below 1.00 indicates schedule underperformance.</td></tr><tr><td>Cost Performance Index</td><td>EV ÷ AC</td><td>'+(cpi?cpi.toFixed(2):'—')+'</td><td>1.00 is on plan; below 1.00 indicates cost inefficiency.</td></tr>';
 $('forecastRows').innerHTML='<tr><td>Estimate at Completion</td><td>BAC ÷ CPI</td><td>'+money(eac)+'</td><td>Simple forecast assuming current cost efficiency continues.</td></tr><tr><td>Estimate to Complete</td><td>EAC − AC</td><td>'+money(etc)+'</td><td>Expected additional cost from the current point.</td></tr><tr><td>Variance at Completion</td><td>BAC − EAC</td><td>'+money(vac)+'</td><td>Positive means forecast under budget; negative means over budget.</td></tr><tr><td>To-Complete Performance Index to BAC</td><td>(BAC − EV) ÷ (BAC − AC)</td><td>'+(tcpiB?tcpiB.toFixed(2):'—')+'</td><td>Efficiency required on remaining work to still hit BAC.</td></tr><tr><td>To-Complete Performance Index to EAC</td><td>(BAC − EV) ÷ (EAC − AC)</td><td>'+(tcpiE?tcpiE.toFixed(2):'—')+'</td><td>Efficiency implied by the current EAC forecast.</td></tr>';
 let parts=[]; if(spi&&spi<1)parts.push('schedule is behind plan'); else if(spi)parts.push('schedule is at or ahead of plan'); if(cpi&&cpi<1)parts.push('cost efficiency is below plan'); else if(cpi)parts.push('cost efficiency is at or above plan');
 $('evmInsight').innerHTML='<strong>Health interpretation:</strong> '+(parts.length?parts.join(' and ')+'.':'Check the inputs; PV and AC must be greater than zero for index calculations.')+' Use EVM as a trend and decision signal, not as a substitute for delivery conversations.';
}
['pv','ev','ac','bac','duration','durationUnit'].forEach(id=>$(id).addEventListener('input',calc)); calc();
})();
