window.jqlRecipes = [
{n:1,q:'issue in subtask("assignee = username1")',p:'Fetch sub-tasks assigned to a user and identify their parent stories.',c:'Sub-task / Parent'},
{n:2,q:'issue in subtask("assignee = snsgari8") AND project = "JIRA-PROJECT-SPACE" AND status NOT IN (Done) AND issuetype IN (Story, Sub-task, Bug)',p:'Find non-Done issues in a specific project for a particular assignee.',c:'Project / Status'},
{n:3,q:'project IN (Project1, "Project2", Project4) AND Sprint = "type sprint name" AND issuetype != Sub-task',p:'Find issues still associated with a sprint, including cases where completed items may need cleanup before sprint start.',c:'Sprint Management'},
{n:4,q:'issue in structure("new PROJECT2 Program Structure", "child of (child of (PROJECT2-11087))")',p:'Navigate the Theme Feature → Epic hierarchy and find descendants below a supplied Theme.',c:'Hierarchy / Structure'},
{n:5,q:'issue in structure("new PROJECT2 Program Structure", "child of (PROJECT2-11279) AND fixVersion = \\"Release 3.1\\"") AND "Epic Link" IN (PROJECT2-11920, PROJECT2-11466)',p:'Find issues under a structure node and release version, constrained by Epic Link.',c:'Hierarchy / Release'},
{n:6,q:'issue in structure("new PROJECT2 Program Structure", "child of (child of (child of (PROJECT2-19087)))") AND issuetype = Bug',p:'Find all Bugs beneath a Theme using the Theme → Feature → Epic hierarchy.',c:'Hierarchy / Bugs'},
{n:7,q:'project IN (Project1, Project4, "Project2") AND issue in hasOpenPR() AND assignee IN (User1, User2, User3)',p:'Find open pull requests associated with team members.',c:'Pull Requests'},
{n:8,q:'project IN (Project1, Project4, "Project2") AND Team = YODHA AND issuetype IN (Story, Bug, Task) AND Sprint IN openSprints() AND Sprint IN closedSprints()',p:'Identify spill-over stories that have sprint history involving closed and current/open sprints.',c:'Sprint / Spill-over'},
{n:9,q:'issue in subtask("fixVersion = product-version-1.4.0")',p:'Identify stories whose sub-tasks are associated with a known Fix Version.',c:'Release / Sub-task'},
{n:10,q:'project = Project1 AND summary ~ "CAN BE REUSED"',p:'Search historical Jira items using a known keyword.',c:'Search / Reuse'},
{n:11,q:'issue in structure("new PROJECT2 Program Structure", "child of (child of (child of (PROJECT2-19087))) AND child of fixVersion = \\"Release 2.0\\" AND issueLinkType IN (\\"depends on\\") AND status IN (New, \\"In Progress\\")")',p:'Identify dependent stories in a structure that are still New or In Progress.',c:'Dependencies'},
{n:12,q:'parent IN (PROJECT1-1399, PROJECT1-1261)',p:'Display sub-tasks belonging to multiple parent stories.',c:'Sub-task / Parent'},
{n:13,q:'parent in structure("new PROJECT2 Program Structure")',p:'Find issues whose parent is represented in the specified structure.',c:'Hierarchy / Parent'},
{n:14,q:'issue in issuesWhere(pick("Labels = V_Listed"))',p:'Display stories under an Epic with the specified label.',c:'Label / Epic'},
{n:15,q:'issue in issuesWhere(pick(\'issue in structure("new PROJECT2 Program Structure", "child of (child of (PROJECT2-11087))") AND fixVersion = "Release 5"\'))',p:'Retrieve issues below a structure node for a particular release.',c:'Hierarchy / Release'},
{n:16,q:'Use the Odyssey / Multiple Teams setup query documented in the referenced Atlassian page.',p:'JQL guidance for a Multiple Teams setup using a single Odyssey Product.',c:'Team Setup',note:'The source document does not include the actual query text for this recipe; it points to the referenced Atlassian guidance.'},
{n:17,q:'project IN (Project1, Project4, "Project3", "Project2") AND issuetype NOT IN ("New Feature", Theme) AND (Team = YODHA OR project = Project1) AND (Team IS EMPTY OR Team = YODHA) ORDER BY Rank ASC',p:'Board filter for issues across multiple Odyssey spaces while retaining team ownership and ranking.',c:'Board / Team'},
{n:18,q:'project IN (Project1, Project4) AND summary ~ "bank" AND issuetype = Story AND attachments IS NOT EMPTY',p:'Search for Stories containing a keyword and having attachments.',c:'Search / Attachments'},
{n:19,q:'project IN (Project1, "Project2", Project4) AND issuetype = Sub-task AND status CHANGED AFTER startOfMonth() BEFORE endOfMonth() AND status IN (Done, "In RC", Ready, Released, "Ready for RC") AND Team = YODHA',p:'Find sub-tasks that changed status during the current month and reached specified delivery states.',c:'Status History'},
{n:20,q:'issuetype = Bug AND status CHANGED TO Done DURING ("2021/02/28", "2021/04/01") AND project = TOM AND environment ~ "PRODUCTION"',p:'Find production Bugs that transitioned to Done during a specified date range.',c:'Status History / Bugs'},
{n:21,q:'issuetype = Bug AND status WAS IN ("In Progress") DURING ("2021/02/28", "2021/04/01") AND project = TOM AND environment ~ "PRODUCTION"',p:'Find production Bugs that were In Progress at some point during a date range, regardless of current status.',c:'Status History / Bugs'},
{n:22,q:'assignee IN (inactiveUsers()) AND project = Project1',p:'Find issues assigned to inactive users or people who have left the organization.',c:'User Management'},
{n:23,q:'issue in issuesWhere(pick("key in (PROJECT2-16023)"))',p:'Find all child issues under a specified Epic.',c:'Epic / Children'},
{n:24,q:'project = ABC AND Sprint IN openSprints() ORDER BY Rank ASC',p:'Show all issues in the currently active sprint, ordered by backlog rank.',c:'Sprint'},
{n:25,q:'assignee IS EMPTY AND project = ABC AND statusCategory != Done',p:'Find unassigned active work that may need ownership.',c:'Ownership'},
{n:26,q:'project = ABC AND statusCategory != Done AND dueDate < now()',p:'Find active issues whose due date has already passed.',c:'Due Dates'},
{n:27,q:'project = ABC AND updated >= -7d ORDER BY updated DESC',p:'Find issues updated in the last seven days; useful for weekly reviews.',c:'Activity'},
{n:28,q:'project = ABC AND created >= -30d ORDER BY created DESC',p:'Find recently created issues.',c:'Search / Reporting'},
{n:29,q:'project = ABC AND priority IN (Highest, High) AND statusCategory != Done',p:'Find high-priority active work requiring attention.',c:'Priority'},
{n:30,q:'project = ABC AND labels IN (blocked, impediment) AND statusCategory != Done',p:'Find active work explicitly marked as blocked or impeded.',c:'Impediments'},
{n:31,q:'project = ABC AND issuetype = Story AND "Story Points" IS EMPTY AND statusCategory != Done',p:'Find active Stories missing Story Points before sprint planning.',c:'Backlog Quality'},
{n:32,q:'project = ABC AND issuetype = Story AND assignee IS EMPTY AND statusCategory != Done',p:'Find active Stories without an owner.',c:'Backlog Quality'},
{n:33,q:'project = ABC AND fixVersion = "Release 1.0" AND statusCategory != Done',p:'Show incomplete work targeted for a release.',c:'Release'},
{n:34,q:'project = ABC AND Sprint IS EMPTY AND statusCategory != Done ORDER BY Rank ASC',p:'Find active backlog items that are not assigned to a sprint.',c:'Backlog'},
{n:35,q:'project = ABC AND issuetype = Bug AND priority IN (Highest, High) AND statusCategory != Done',p:'Find high-priority unresolved defects.',c:'Defects'},
{n:36,q:'project = ABC AND statusCategory = Done AND resolved >= -14d ORDER BY resolved DESC',p:'Show work completed in the last two weeks.',c:'Reporting'},
{n:37,q:'project = ABC AND resolution IS EMPTY AND statusCategory = Done',p:'Detect Done issues that may have an incomplete resolution field.',c:'Data Quality'},
{n:38,q:'project = ABC AND issuetype = Story AND statusCategory != Done AND summary ~ "login"',p:'Search active Stories containing a keyword in the summary.',c:'Search'},
{n:39,q:'project = ABC AND component = "Payments" AND statusCategory != Done',p:'Find active issues belonging to a specific component.',c:'Component'},
{n:40,q:'project = ABC AND issuetype = Bug AND environment ~ "PRODUCTION" AND created >= -30d',p:'Find production-related Bugs created in the last 30 days.',c:'Production / Bugs'}
];
window.jqlUsage = [
{a:'Daily Scrum',what:'Active sprint + blocked items + unassigned items',ids:[24,25,30]},
{a:'Sprint Planning',what:'Backlog items without sprint, missing Story Points, high-priority work',ids:[29,31,34]},
{a:'Backlog Refinement',what:'Unestimated Stories, unowned Stories, keyword searches, old/inactive work',ids:[25,31,32,38]},
{a:'Sprint Review',what:'Completed work and release-targeted work',ids:[33,36]},
{a:'Retrospective',what:'Spill-over, status history, recently updated items',ids:[8,19,27]},
{a:'Release Readiness',what:'Incomplete release scope, production Bugs, dependency issues',ids:[11,20,21,33,40]},
{a:'Jira Hygiene',what:'Inactive users, Done-without-resolution, stale sprint assignments',ids:[3,22,37]},
{a:'Team / Board Administration',what:'Multiple teams, board filters, rank ordering',ids:[16,17]}
];
window.jqlSyntax = [
['=','Exact match','status = "In Progress"'],['!=','Not equal','issuetype != Sub-task'],['IN','Match one of several values','priority IN (Highest, High)'],['NOT IN','Exclude several values','status NOT IN (Done, Closed)'],['IS EMPTY','Field has no value','assignee IS EMPTY'],['IS NOT EMPTY','Field has a value','attachments IS NOT EMPTY'],['~','Contains / text search','summary ~ "payment"'],['AND / OR','Combine conditions','project = ABC AND status != Done'],['ORDER BY','Sort results','ORDER BY updated DESC'],['WAS / CHANGED','Search status history','status WAS "In Progress"'],['DURING','Limit history to a date range','status CHANGED TO Done DURING ("2026/08/01", "2026/08/31")'],['startOfMonth()','Beginning of current month','updated >= startOfMonth()'],['openSprints()','Currently active sprints','Sprint IN openSprints()'],['closedSprints()','Completed/closed sprints','Sprint IN closedSprints()']
];
