
(function(){
 const b=window.siteBase?siteBase():'/agile-orbit/';
 document.addEventListener('DOMContentLoaded',()=>{
  const footer=document.getElementById('site-footer'); if(footer)footer.innerHTML=`<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="${b}"><span class="brand-mark"></span><span>AGILE ORBIT</span></a><p class="muted">Learn Agile. Think Better. Lead Differently.</p><p class="note">A practical toolkit for people helping teams and organisations work better.</p></div><div><strong>Explore</strong><div class="footer-links"><a href="${b}learn/">Learn</a><a href="${b}tools/">Tools</a><a href="${b}resources/">Resources</a><a href="${b}practice/">Practice</a><a href="${b}insights/">Insights</a></div></div><div><strong>About</strong><div class="footer-links"><a href="${b}about/journey.html">My Journey</a><a href="${b}about/linkedin.html">LinkedIn</a><a href="${b}about/mindmap.html">Mindmap</a><a href="${b}about/credly.html">Credly</a></div></div><div><strong>Connect</strong><div class="footer-links"><a href="${b}connect/contact.html">Contact</a><a href="${b}connect/feedback.html">Feedback</a><a href="${b}connect/linkedin.html">LinkedIn</a></div></div></div><div class="footer-bottom"><span>© ${SITE_CONFIG.year} Agile Orbit</span><span>Built for Agile practitioners. <a href="#" id="backTop">Back to top ↑</a></span></div></div></footer>`;
  document.getElementById('backTop')?.addEventListener('click',e=>{e.preventDefault();scrollTo({top:0,behavior:'smooth'});});
  const theme=localStorage.getItem('agile-orbit-theme')||'dark'; document.documentElement.dataset.theme=theme;
  document.getElementById('themeBtn')?.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('agile-orbit-theme',n);});
  document.querySelectorAll('.card').forEach(c=>c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',`${e.clientX-r.left}px`);c.style.setProperty('--my',`${e.clientY-r.top}px`);}));
  const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
  document.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count);let done=false;const o=new IntersectionObserver(es=>{if(es[0].isIntersecting&&!done){done=true;let n=0;const step=Math.max(1,Math.ceil(target/35));const t=setInterval(()=>{n=Math.min(target,n+step);el.textContent=n+(el.dataset.suffix||'');if(n>=target)clearInterval(t)},25)}},{threshold:.8});o.observe(el);});
 });
})();
