(function(){
  const rootName='/agile-orbit/';
  function base(){const p=location.pathname; const i=p.indexOf(rootName); return i>=0?p.slice(0,i)+rootName:'./';}
  window.siteBase=base;
  const b=base();
  function ensureNavStyles(){const href=b+'css/hero-nav.css';if(!Array.from(document.querySelectorAll('link[rel="stylesheet"]')).some(link=>link.href===new URL(href,location.href).href)){const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link);}}
  ensureNavStyles();
  const navChildren={
    learn:[['Behavioural Psychology','learn/behavioural-psychology/'],['Science Behind Agile','learn/science-behind-agile/'],['Facilitation','learn/facilitation/',[['Scrum Event Facilitation','learn/facilitation/scrum-event.html'],['Facilitation Techniques','learn/facilitation/techniques.html']]]],
    tools:[['Sprint Capacity','tools/sprint-capacity.html'],['Flow Efficiency','tools/flow-efficiency.html'],['WSJF Calculator','tools/wsjf-calculator.html'],['Cost of Delay','tools/cost-of-delay.html'],['Meeting Cost','tools/meeting-cost.html'],['Team Health Check','tools/team-health-check.html'],['PI Planning Capacity','tools/pi-planning-capacity.html'],['Release Forecast','tools/release-forecast.html'],['Earned Value Management','tools/earned-value.html']],
    resources:[['Retrospectives','resources/retrospectives/'],['Templates','resources/templates/'],['AI for Agile','resources/ai-for-agile/'],['Recommended Books','resources/books/'],['Advanced JQL','resources/jql/']],
    insights:[['Why Agile Transformations Fail','insights/agile-in-practice.html'],['Context Beats Control','insights/leadership.html'],['Velocity Is Not Productivity','insights/behaviour-psychology.html'],['The Coach as System Mirror','insights/coaching.html'],['Flow Before Forecasts','insights/product-delivery.html'],['What AI Means for Scrum Masters','insights/ai-agile.html'],['Lessons Learned in Public','insights/lessons-learned.html']],
    coaching:[['Coaching Approach','coaching/coaching-approach.html'],['Coaching Canvas','coaching/coaching-canvas.html'],['Coaching Questions','coaching/coaching-questions.html'],['Team Coaching','coaching/team-coaching.html'],['Leadership Coaching','coaching/leadership-coaching.html'],['Agile Transformation','coaching/agile-transformation.html']]
  };
  function menuMarkup(section){const items=navChildren[section];if(!items?.length)return '';return `<div class="nav-dropdown" role="menu" aria-label="${section} pages">${items.map(([label,path,children])=>children?`<div class="nav-submenu-item"><a class="nav-submenu-label" href="${b}${path}" role="menuitem" aria-haspopup="true">${label}<span class="nav-submenu-caret" aria-hidden="true">›</span></a><div class="nav-submenu" role="menu" aria-label="${label} pages">${children.map(([childLabel,childPath])=>`<a href="${b}${childPath}" role="menuitem">${childLabel}</a>`).join('')}</div></div>`:`<a href="${b}${path}" role="menuitem">${label}</a>`).join('')}</div>`;}
  const nav=document.getElementById('site-nav');
  if(nav){nav.innerHTML=`<header class="site-header" id="siteHeader"><div class="container nav"><a class="brand" href="${b}" aria-label="Agile Orbit home"><span class="brand-mark" aria-hidden="true"></span><span>AGILE ORBIT</span></a><nav class="nav-links" aria-label="Primary"><div class="nav-item has-dropdown"><a class="nav-link" data-section="learn" href="${b}learn/" aria-haspopup="true">Learn<span class="nav-caret" aria-hidden="true">⌄</span></a>${menuMarkup('learn')}</div><div class="nav-item has-dropdown"><a class="nav-link" data-section="tools" href="${b}tools/" aria-haspopup="true">Tools<span class="nav-caret" aria-hidden="true">⌄</span></a>${menuMarkup('tools')}</div><div class="nav-item"><a class="nav-link" data-section="practice" href="${b}practice/">Practice</a></div><div class="nav-item has-dropdown"><a class="nav-link" data-section="resources" href="${b}resources/" aria-haspopup="true">Resources<span class="nav-caret" aria-hidden="true">⌄</span></a>${menuMarkup('resources')}</div><div class="nav-item has-dropdown"><a class="nav-link" data-section="insights" href="${b}insights/" aria-haspopup="true">Insights<span class="nav-caret" aria-hidden="true">⌄</span></a>${menuMarkup('insights')}</div><div class="nav-item has-dropdown"><a class="nav-link" data-section="coaching" href="${b}coaching/" aria-haspopup="true">Coaching<span class="nav-caret" aria-hidden="true">⌄</span></a>${menuMarkup('coaching')}</div><div class="nav-item"><a class="nav-link" data-section="about" href="${b}about/">About</a></div></nav><div class="nav-actions"><button class="icon-btn search-icon" id="searchBtn" aria-label="Search" aria-controls="siteSearch" aria-expanded="false">⌕</button><button class="icon-btn mobile-toggle" id="mobileBtn" aria-label="Open menu">☰</button></div></div></header>`;}
  const drawer=document.getElementById('mobile-drawer');
  if(drawer){const mobileSections=['learn','tools','practice','resources','insights','coaching','about'];const mobileMarkup=mobileSections.map(section=>{const label=section.charAt(0).toUpperCase()+section.slice(1),children=navChildren[section];if(!children)return `<a href="${b}${section}/">${label}</a>`;return `<details class="mobile-nav-group"><summary>${label}</summary><a class="mobile-nav-parent" href="${b}${section}/">Open ${label}</a>${children.map(([name,path,nested])=>nested?`<details class="mobile-nav-subgroup"><summary><a href="${b}${path}">${name}</a></summary>${nested.map(([childName,childPath])=>`<a href="${b}${childPath}">${childName}</a>`).join('')}</details>`:`<a href="${b}${path}">${name}</a>`).join('')}</details>`;}).join('');drawer.innerHTML=`<div class="mobile-drawer-inner"><div class="drawer-head"><strong>AGILE ORBIT</strong><button class="icon-btn" id="drawerClose" aria-label="Close menu">×</button></div><a href="${b}">Home</a>${mobileMarkup}</div>`;}
  const seedPaths=['learn/','tools/','practice/','resources/','insights/','coaching/','about/'];let searchIndex=null,searchBuilding=null;
  function cleanText(el){return (el?.textContent||'').replace(/\s+/g,' ').trim();}
  function absolutePath(href){try{const u=new URL(href,location.href);if(u.origin!==location.origin)return null;const root=new URL(b,location.href);if(u.pathname!==root.pathname&&!u.pathname.startsWith(root.pathname))return null;return u.pathname+u.search;}catch{return null;}}
  function makeEntry(url,doc,card){const title=cleanText(card?.querySelector('h1,h2,h3,h4'))||cleanText(doc.querySelector('h1'))||doc.title.replace(/\s*\|.*$/,'').trim();if(!title)return null;const text=cleanText(card||doc.querySelector('main')||doc.body).slice(0,1800),href=card?.getAttribute('href'),target=href?absolutePath(href):url;if(!target)return null;return {title,url:target,keywords:text};}
  async function buildSearchIndex(){if(searchIndex)return searchIndex;if(searchBuilding)return searchBuilding;searchBuilding=(async()=>{const queue=seedPaths.map(p=>b+p),seen=new Set(),entries=new Map(),maxPages=180;while(queue.length&&seen.size<maxPages){const batch=queue.splice(0,8).filter(u=>!seen.has(u));if(!batch.length)continue;const pages=await Promise.all(batch.map(async url=>{seen.add(url);try{const res=await fetch(url,{cache:'no-store'});if(!res.ok||!res.url.includes(rootName))return null;return {url,html:await res.text()};}catch{return null;}}));pages.filter(Boolean).forEach(page=>{const doc=new DOMParser().parseFromString(page.html,'text/html'),main=doc.querySelector('main')||doc.body,pageEntry=makeEntry(page.url,doc,null);if(pageEntry)entries.set(pageEntry.url,pageEntry);main.querySelectorAll('a[href]').forEach(a=>{const target=absolutePath(a.getAttribute('href'));if(!target||target.startsWith(b+'assets/')||target.startsWith(b+'css/')||target.startsWith(b+'js/'))return;const full=new URL(target,location.origin).href;if(!seen.has(full)&&!queue.includes(full)&&queue.length+seen.size<maxPages)queue.push(full);const card=a.matches('.card,.ai-system-card,.theme-card,[class*="card"]')?a:(a.querySelector('h2,h3,h4')?a:null),entry=makeEntry(target,doc,card);if(entry)entries.set(entry.url,entry);});});}searchIndex=Array.from(entries.values()).filter((item,i,arr)=>arr.findIndex(x=>x.url===item.url&&x.title===item.title)===i);return searchIndex;})();return searchBuilding;}
  function ensureSearch(){if(document.getElementById('siteSearch'))return;const overlay=document.createElement('div');overlay.id='siteSearch';overlay.className='site-search';overlay.innerHTML=`<div class="site-search-backdrop" data-search-close></div><section class="site-search-panel" role="dialog" aria-modal="true" aria-labelledby="siteSearchTitle"><div class="site-search-head"><div><span class="site-search-kicker">AGILE ORBIT</span><h2 id="siteSearchTitle">Search the Orbit</h2></div><button class="icon-btn" data-search-close aria-label="Close search">×</button></div><label class="site-search-field"><span aria-hidden="true">⌕</span><input id="siteSearchInput" type="search" autocomplete="off" placeholder="Search Agile, Scrum, SAFe, prompts, calculators…" aria-label="Search Agile Orbit"><kbd>ESC</kbd></label><div id="siteSearchResults" class="site-search-results" aria-live="polite"></div></section>`;document.body.appendChild(overlay);const input=overlay.querySelector('#siteSearchInput'),results=overlay.querySelector('#siteSearchResults');function render(items,query){const q=query.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean),matches=terms.length?items.filter(item=>{const haystack=(item.title+' '+item.keywords).toLowerCase();return terms.every(term=>haystack.includes(term));}):items.slice(0,30);results.innerHTML=matches.length?matches.slice(0,40).map(item=>`<a class="site-search-result" href="${item.url}"><span class="site-search-result-mark" aria-hidden="true">✦</span><span><strong>${item.title}</strong><small>${item.keywords.slice(0,150)}${item.keywords.length>150?'…':''}</small></span><span aria-hidden="true">→</span></a>`).join(''):`<div class="site-search-empty">No matching content found. Try a card title, topic, tool name, prompt, framework or Scrum event.</div>`;}async function openSearch(){overlay.classList.add('open');document.getElementById('searchBtn')?.setAttribute('aria-expanded','true');results.innerHTML='<div class="site-search-empty">Indexing Agile Orbit content…</div>';requestAnimationFrame(()=>input.focus());const items=await buildSearchIndex();render(items,input.value);}function closeSearch(){overlay.classList.remove('open');document.getElementById('searchBtn')?.setAttribute('aria-expanded','false');}input.addEventListener('input',async()=>render(await buildSearchIndex(),input.value));overlay.addEventListener('click',e=>{if(e.target.closest('[data-search-close]'))closeSearch();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();});document.addEventListener('click',e=>{if(e.target.closest('#searchBtn'))openSearch();});}
  ensureSearch();
  function enhanceFacilitationTechniqueCartoons(){
    if(!location.pathname.includes('/learn/facilitation/techniques.html'))return;
    const files=['01-1-2-4-All.png','02-Roman-Voting.png','03-Dot-Voting.png','04-Fist-of-Five.png','05-Affinity-Mapping.png','06-Gallery-Walk.png','07-White-Elephant.png','08-Diverge-Converge.png','09-TRIZ.png','10-Team-Agreement.png','11-Thirty-Five.png','12-Buy-a-Feature.png'];
    const rawBase='https://raw.githubusercontent.com/agilecoach-ashutosh/agile-orbit/main/assets/images/facilitation/';
    const style=document.createElement('style');
    style.textContent='.tech-visual.tech-cartoon-visual{padding:0!important;background:#fff!important;border:1px solid rgba(255,255,255,.16)!important;overflow:hidden;min-height:260px!important}.tech-cartoon-visual img{display:block;width:100%;height:100%;min-height:260px;object-fit:contain;border-radius:15px}.tech-cartoon-visual>*{margin:0!important}@media(max-width:800px){.tech-cartoon-visual img{min-height:220px}}';
    document.head.appendChild(style);
    document.querySelectorAll('.tech-slide .tech-visual').forEach((el,i)=>{
      const file=files[i];if(!file)return;
      const img=document.createElement('img');
      img.src=rawBase+encodeURIComponent(file)+'?v=20260907';
      img.alt='Hand-drawn visual for '+(document.querySelectorAll('.tech-slide')[i]?.querySelector('.tech-title')?.textContent||'facilitation technique');
      img.loading=i===0?'eager':'lazy';img.decoding='async';
      img.addEventListener('error',()=>{img.src=b+'assets/images/facilitation/'+file+'?v=20260907';});
      el.classList.add('tech-cartoon-visual');el.replaceChildren(img);
    });
  }
  function markActive(){const path=location.pathname;document.querySelectorAll('[data-section]').forEach(el=>{const s=el.dataset.section;if(path.includes('/'+s+'/'))el.classList.add('active');});}
  document.addEventListener('click',e=>{if(e.target.closest('#mobileBtn'))document.getElementById('mobile-drawer')?.classList.add('open');if(e.target.closest('#drawerClose'))document.getElementById('mobile-drawer')?.classList.remove('open');if(e.target.closest('.mobile-drawer-inner a'))document.getElementById('mobile-drawer')?.classList.remove('open');});
  window.addEventListener('scroll',()=>document.getElementById('siteHeader')?.classList.toggle('scrolled',scrollY>10),{passive:true});
  document.addEventListener('DOMContentLoaded',()=>{markActive();enhanceFacilitationTechniqueCartoons();});
  if(document.readyState!=='loading')enhanceFacilitationTechniqueCartoons();
})();