(function(){
'use strict';
const EXCLUDED_IDS=new Set(['Q-440FAE3F','Q-5AB227CA','Q-49A23550','Q-7D1F260D']);
const Q=(window.PRACTICE_QUESTIONS||[]).filter(q=>!EXCLUDED_IDS.has(q.id)).map(q=>q.id==='Q-72214BA4'?{...q,options:['Transparency','Adaptation','Cross-functionality','Self-organization','Inspection'],correctAnswer:'A, B, E',correctOptionText:'Transparency | Adaptation | Inspection'}:q);
const panel=document.getElementById('quiz-panel'),grid=document.getElementById('themeGrid');
const themes=[['Scrum Fundamentals','Build a strong foundation in Scrum accountabilities, artifacts, values and core concepts.'],['Scrum Events','Practice Sprint Planning, Daily Scrum, Sprint Review and Retrospective thinking.'],['Product Backlog & Refinement','Strengthen backlog ordering, refinement, slicing, clarity and readiness.'],['Product Owner & Product Management','Explore Product Owner decisions, value, stakeholders and product thinking.'],['Facilitation & Collaboration','Practice facilitation, collaboration, conflict and team interaction scenarios.'],['Agile Leadership','Test servant leadership, coaching, empowerment and organisational leadership thinking.'],['Evidence-Based Management & Metrics','Practice evidence, outcomes, metrics and Evidence-Based Management concepts.'],['Scaling Scrum','Explore Nexus and scaling Scrum concepts and coordination.'],['SAFe 6.0','Practice SAFe 6.0 concepts, Lean-Agile principles, roles, flow, PI Planning and portfolio thinking.']];
const icons=['01','02','03','04','05','06','07','08','09'];
themes.forEach((t,i)=>{const n=Q.filter(x=>x.theme===t[0]).length;const b=document.createElement('button');b.className='theme-card';b.innerHTML=`<span class="theme-number">${icons[i]} · ORBIT</span><h3>${t[0]}</h3><p>${t[1]}</p><span class="count">${n} questions</span><span class="arrow">↗</span>`;b.onclick=()=>openSetup(t[0]);grid.appendChild(b)});
function openSetup(theme){const pool=Q.filter(x=>x.theme===theme);panel.hidden=false;panel.innerHTML=`<div class="quiz-shell"><div class="quiz-top"><div><div class="quiz-kicker">Practice setup</div><div class="quiz-title">${theme}</div><div class="muted">${pool.length} questions available</div></div><button class="quiz-close" id="closeQuiz">Close ×</button></div><div class="setup-grid"><div class="setup-card"><h3>How do you want to practice?</h3><p class="muted">Choose the number of questions, difficulty and mode.</p><label>Questions<select id="qCount"><option value="10">10</option><option value="20">20</option><option value="30">30</option><option value="50">50</option><option value="all">All available</option></select></label><br><label>Difficulty<select id="difficulty"><option value="All">All difficulties</option><option value="Foundation">Foundation</option><option value="Practitioner">Practitioner</option></select></label><br><label>Mode<select id="mode"><option value="practice">Practice — instant feedback</option><option value="exam">Exam — review at the end</option></select></label><div class="setup-actions"><button class="btn btn-primary" id="startQuiz">Start Practice 🚀</button></div></div><div class="setup-card"><h3>What you'll get</h3><ul><li>Random question selection</li><li>Single and multiple-answer questions supported</li><li>Practice mode explains the answer immediately</li><li>Exam mode keeps feedback until submission</li><li>Results show topic performance</li></ul></div></div></div>`;document.getElementById('closeQuiz').onclick=()=>panel.hidden=true;document.getElementById('startQuiz').onclick=()=>startQuiz(theme,pool)}
function startQuiz(theme,pool){let d=document.getElementById('difficulty').value;let p=pool.filter(x=>d==='All'||x.difficulty===d);if(!p.length)p=pool;let n=document.getElementById('qCount').value==='all'?p.length:Math.min(+document.getElementById('qCount').value,p.length);p=p.sort(()=>Math.random()-.5).slice(0,n);let mode=document.getElementById('mode').value;renderQuestion({theme,questions:p,mode,index:0,answers:[],score:0})}
function letters(answer){return String(answer||'').split(/[^A-E]+/).filter(Boolean)}
function renderQuestion(s){let q=s.questions[s.index],opts=q.options.map((o,i)=>o?`<button class="answer ${s.answers[s.index]?.includes(String.fromCharCode(65+i))?'selected':''}" data-letter="${String.fromCharCode(65+i)}"><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`:'').join('');panel.innerHTML=`<div class="quiz-shell"><div class="quiz-top"><div><div class="quiz-kicker">${s.theme} · ${s.mode==='exam'?'Exam':'Practice'}</div><div class="quiz-title">Question ${s.index+1} of ${s.questions.length}</div></div><button class="quiz-close" id="quitQuiz">Quit ×</button></div><div class="quiz-progress"><span>${Math.round((s.index/s.questions.length)*100)}%</span><div class="progress-bar"><div class="progress-fill" style="width:${((s.index+1)/s.questions.length)*100}%"></div></div></div><div class="question-card"><div class="muted">${q.difficulty} · ${letters(q.correctAnswer).length>1?'Select all that apply':'Select one answer'}</div><h2>${q.question}</h2><div class="answers">${opts}</div><div id="feedback"></div><div class="quiz-actions"><button class="btn" id="backBtn" ${s.index===0?'disabled':''}>← Previous</button><button class="btn btn-primary" id="nextBtn">${s.index===s.questions.length-1?'Finish':'Next →'}</button></div></div></div>`;panel.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>choose(s,btn.dataset.letter));document.getElementById('backBtn').onclick=()=>{if(s.index>0){s.index--;renderQuestion(s)}};document.getElementById('nextBtn').onclick=()=>next(s);document.getElementById('quitQuiz').onclick=()=>openSetup(s.theme)}
function choose(s,l){let q=s.questions[s.index],multi=letters(q.correctAnswer).length>1,a=s.answers[s.index]||[];if(!multi)a=[l];else a=a.includes(l)?a.filter(x=>x!==l):[...a,l];s.answers[s.index]=a;renderQuestion(s);if(s.mode==='practice')showFeedback(s)}
function showFeedback(s){let q=s.questions[s.index],chosen=s.answers[s.index]||[];if(!chosen.length)return;let corr=letters(q.correctAnswer).sort().join(''),got=[...chosen].sort().join('');document.getElementById('feedback').innerHTML=`<div class="feedback"><strong>${corr===got?'Correct ✓':'Review this answer'}</strong><p>${q.correctOptionText||'The correct option is marked in the question bank.'}</p></div>`;panel.querySelectorAll('.answer').forEach(b=>{let l=b.dataset.letter;if(letters(q.correctAnswer).includes(l))b.classList.add('correct');else if(chosen.includes(l))b.classList.add('incorrect')})}
function next(s){let chosen=s.answers[s.index]||[];if(!chosen.length){document.getElementById('feedback').innerHTML='<div class="feedback">Please select an answer before continuing.</div>';return}if(s.index===s.questions.length-1){finish(s);return}s.index++;renderQuestion(s)}
function finish(s){let correct=0;const topic={};s.questions.forEach((q,i)=>{let ok=[...letters(q.correctAnswer)].sort().join('')===[...(s.answers[i]||[])].sort().join('');if(ok)correct++;topic[q.subtheme||q.theme]??={c:0,n:0};topic[q.subtheme||q.theme].n++;if(ok)topic[q.subtheme||q.theme].c++});let pct=Math.round(correct/s.questions.length*100);panel.innerHTML=`<div class="quiz-shell"><div class="quiz-top"><div><div class="quiz-kicker">Practice complete</div><div class="quiz-title">${s.theme}</div></div><button class="quiz-close" id="resultClose">Close ×</button></div><div class="results-head"><div class="score-ring" style="--score:${pct}%"><strong>${pct}%</strong></div><h1>${correct} / ${s.questions.length}</h1><p class="muted">${pct>=80?'Strong performance. Keep challenging your thinking.':pct>=60?'Good foundation. Review the questions you missed.':'Use the misses as your learning map — then try again.'}</p></div><div class="result-grid"><div class="metric"><strong>${correct}</strong>Correct</div><div class="metric"><strong>${s.questions.length-correct}</strong>To review</div><div class="metric"><strong>${s.questions.length}</strong>Attempted</div></div><div class="result-card" style="margin-top:18px"><h3>Performance by topic</h3><div class="topic-bars">${Object.entries(topic).map(([k,v])=>`<div class="topic-row"><span>${k}</span><div class="topic-bar"><span style="width:${v.c/v.n*100}%"></span></div><strong>${Math.round(v.c/v.n*100)}%</strong></div>`).join('')}</div></div><div class="setup-actions"><button class="btn btn-primary" id="retry">Retry</button><button class="btn" id="homePractice">Choose another theme</button></div></div>`;document.getElementById('resultClose').onclick=()=>panel.hidden=true;document.getElementById('homePractice').onclick=()=>panel.hidden=true;document.getElementById('retry').onclick=()=>startQuiz(s.theme,Q.filter(x=>x.theme===s.theme))}
})();
