const {JSDOM}=require('jsdom');const fs=require('fs'),assert=require('assert');const root=require('path').resolve(__dirname,'..')+'/';
const heroMobileCss=fs.readFileSync(root+'css/hero-mobile.css','utf8'),heroAiCss=fs.readFileSync(root+'css/hero-ai-fix.css','utf8'),heroScrollCss=fs.readFileSync(root+'css/hero-scroll.css','utf8'),heroScript=fs.readFileSync(root+'js/hero-scroll.js','utf8'),homeHtml=fs.readFileSync(root+'index.html','utf8');
assert(!heroMobileCss.includes('font-size:.29rem'),'Hero mobile copy must remain legible');
assert(heroMobileCss.includes('min-height:44px!important;height:44px!important'),'Hero CTA must retain a 44px touch target');
assert(!heroScrollCss.includes('hero-var('),'Hero title color token must be valid');\nassert(heroAiCss.includes('object-position:right center!important'),'Desktop AI artwork must retain its right-edge safe area');\nassert(!heroAiCss.includes('translate3d(-7vw,0,0)'),'Desktop AI artwork must not be shifted outside its frame');\nassert(heroAiCss.includes('ai-panel-body{font-size:.74rem'),'Desktop AI panel copy must remain legible');
assert(heroScript.includes('warmNext(base)'),'The next hero scene must be prepared before its transition');
assert(!homeHtml.includes('src="js/tools.js"'),'Homepage must not load the page-specific tools bundle');
assert.equal((homeHtml.match(/rel="preload"/g)||[]).length,1,'Homepage should preload only the LCP hero image');
console.log('Hero readability, touch-target, media-warming and payload regression checks passed.');
function setup(page,script){const dom=new JSDOM(fs.readFileSync(root+page,'utf8'),{url:'https://agilecoach-ashutosh.github.io/agile-orbit/'+page,runScripts:'outside-only'});dom.window.eval(fs.readFileSync(root+script,'utf8'));const d=dom.window.document;return {dom,d,set(id,value){const el=d.getElementById(id);el.value=String(value);el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));},text(id){return d.getElementById(id).textContent}};}
let t=setup('tools/sprint-capacity.html','js/capacity-planning.js');t.set('velocity-n',0);t.set('velocity-n1',30);t.set('velocity-n2',60);t.set('available-days',70);assert.equal(t.text('prediction-number'),'30');t.set('velocity-n','');assert.equal(t.text('prediction-number'),'45');t.set('velocity-n1',-1);assert.equal(t.text('prediction-number'),'—');t.dom.window.close();
t=setup('resources/templates/capacity-planning.html','js/capacity-planning.js');t.dom.window.close();
t=setup('tools/release-forecast.html','js/release-forecast.js');let inputs=t.d.querySelectorAll('#velocityRows input');[0,30,60].forEach((v,i)=>{inputs[i].value=v;inputs[i].dispatchEvent(new t.dom.window.Event('input'));});assert.equal(t.text('likelySprints'),'4');assert.equal(t.text('consSprints'),'No finite forecast');t.set('backlog',0);assert.equal(t.text('likelySprints'),'0');t.set('backlog',-1);assert.equal(t.text('likelySprints'),'—');t.set('backlog',120);t.set('adjustment',-101);assert.equal(t.text('likelySprints'),'—');t.dom.window.close();
t=setup('tools/pi-planning-capacity.html','js/pi-planning-capacity.js');assert.equal(t.text('kCapacity'),'840');t.set('daysWeek',8);assert.equal(t.text('kCapacity'),'—');t.set('daysWeek',5);t.set('piWeeks',8);t.d.getElementById('resetTeams').click();assert.equal(t.d.getElementById('piWeeks').value,'10');assert.equal(t.text('kCapacity'),'840');const members=t.d.querySelector('.members');members.value='1.5';members.dispatchEvent(new t.dom.window.Event('input'));assert.equal(t.text('kCapacity'),'—');t.dom.window.close();
console.log('Calculator regression tests passed: zero history, blank history, invalid values, empty template context, forecast bounds and complete reset.');
(async()=>{
 const dom=new JSDOM('<!doctype html><html><head></head><body><div id="site-nav"></div><div id="mobile-drawer"></div><main><button id="outside">Outside</button></main></body></html>',{url:'https://agilecoach-ashutosh.github.io/agile-orbit/about/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;
 w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>({ok:true,json:async()=>[{title:'Capacity',url:'tools/sprint-capacity.html',keywords:'capacity'}]});w.eval(fs.readFileSync(root+'js/theme.js','utf8'));w.eval(fs.readFileSync(root+'js/navigation.js','utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));
 assert.equal(d.documentElement.dataset.theme,'dark');d.getElementById('themeBtn').click();assert.equal(d.documentElement.dataset.theme,'light');assert.equal(w.localStorage.getItem('agile-orbit-theme'),'light');
 const search=d.getElementById('searchBtn');search.focus();search.click();await new Promise(r=>setTimeout(r,25));assert(d.querySelector('main').inert);assert.equal(d.activeElement.id,'siteSearchInput');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.activeElement,search);assert(!d.querySelector('main').inert);assert.equal(d.body.style.overflow,'');
 d.getElementById('mobileBtn').focus();d.getElementById('mobileBtn').click();await new Promise(r=>setTimeout(r,25));assert.equal(d.activeElement.id,'drawerClose');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.activeElement.id,'mobileBtn');assert(!d.getElementById('mobile-drawer').classList.contains('open'));
 dom.window.close();console.log('Theme persistence and search/drawer focus, Escape, inert restoration and scroll restoration passed.');
})();
